staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

This doesn't eliminate the callTree (I'm working on that separately), but it does get all calls to ExtractValidations down to 1 per field.

Simplify call tree

---

pkg/apis/core/v1/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/maps/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/one_type_match/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/one_type_match/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/slices/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/slices/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/targets.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go
staging/src/k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1/zz_generated.validations.go

@thockin https://github.com/jpbetz/kubernetes/commit/e4a3429b6144f90e2f22fd99f7c5986a862ff7db could use your eyes.  The problem was simply that the typeNode for types like `string[]` were being written to `typeNodes[]` multiple times, each with different `eachKey` and `eachVal` validations, resulting in the last-writer's value (written to `typesNode`) being used in all generation for that type.
I hacked up a quick fix that moved `eachKey`, `eachVal` propagation onto the stack.  Happy to defer to any approach you'd prefer here, I just wanted to illustrate the bug I found and propose at least one possible fix.

Follow ups: deshare eachKey, eachVal validations between fields of same type, remove dup code

---

staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/aliases/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/aliases/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

I'll still look for a way to do what we want, but it seems like Go doesn't want me to.  Given:
```
type T1 string
type T2 T1
```
T1 and T2 "are unrelated" in the type system.  It's false to think of T2 and derived form of T1.  It's not.  "Go doesn't have inheritance".

Document the typdef-to-typedef behavior

---

TODO.validation-gen
staging/src/k8s.io/code-generator/cmd/validation-gen/main.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/enum.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/openapi.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/registry.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/required.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/testing.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/union.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/validators.go
staging/src/k8s.io/code-generator/go.mod

```
Tag: +eachKey
Description: Declares a validation for map keys.
Attach to:
- type definitions
- field definitions (including map keys and map/slice values)
Tag value(s):
<validation-tag>:  This tag will be evaluated for each key of a map.
Tag: +eachVal
Description: Declares a validation for map and slice values.
Attach to:
- type definitions
- field definitions (including map keys and map/slice values)
Tag value(s):
<validation-tag>:  This tag will be evaluated for each value of a map or slice.
Tag: +enum
Description: Indicates that a string type is an enum. All const values of this type are considered values in the enum.
Attach to:
- type definitions
Tag value(s):
Tag: +k8s:validation::format
Description: Indicates that a string field has a particular format.
Attach to:
- type …
```

Make `validation-gen --docs` print known tags

---

TODO.validation-gen
staging/src/k8s.io/apimachinery/pkg/api/validate/doc.go

The idea here is to simply document a recommended approach for tightened/ratcheting validation.

Document approach to tightened/ratcheting validation

---

TODO.validation-gen

/kind cleanup
This PR goes through the items in the TODO.validation-gen list attempts to prioritize items based on previous discussions, de-dupe some entries, and also show what items are potentially already completed from past PRs.  The goal of this is groom the TODO-list/backlog a bit to simplify taking additional items.  I am also creating issues for each of the TODO items here to add more context for each item.
```release-note
NONE
```
```docs
```

docs: update TODO.validation-gen to add priotization groups and to dedupe a # of items

---

staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go

When we did this, the signatures were compatible, but then they drifted.

Unbreak IsValidIP() for core validation

---

staging/src/k8s.io/code-generator/cmd/validation-gen/targets.go

package-tags have to have a value, but we are checking for empty values wrong.

Fix bug in tags handling

---

staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/recursive/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/recursive/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

If there is no validation on a recursive type, the generator will recurse until it stack-overflows.  Now we track seen types and terminate recursion.

Fix a bug with recursive types

---

pkg/apis/core/v1/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/openapi.go

We don't really benefit from using the OpenAPI extractor.  We don't agree with how it represents enums, and I don't agree with how it handles format either, so let's just parse what we need.  We need to have utilities to do that in general anyway.

Parse maxItems,maxLength and format independently

---

TODO.validation-gen
staging/src/k8s.io/code-generator/cmd/validation-gen/targets.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/registry.go

Since we're using `k8s:` prefixes to selectively enabled declarative validation, we don't need these options.  Removing them simplifies things.

Drop validation-gen-enabled-tags and validation-gen-disabled-tags

---

staging/src/k8s.io/code-generator/cmd/validation-gen/lint.go
staging/src/k8s.io/code-generator/cmd/validation-gen/lint_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/main.go
staging/src/k8s.io/code-generator/cmd/validation-gen/targets.go

/kind feature
Run lint on the comment tags
When flag `--lint-only` tag is added, the validation-gen command would run lint on the targeted packages comment tags and print out the lint errors without executing the code generation.

feat: Add linting functionality to validation-gen with --lint-only flag

---

.github/workflows/validation-gen-ci-test.yml

Currently CI is failing for all PRs due to the "go mod tidy" test. I have removed this test as it seems not helpful in the context of the deps k8s/k8s wants and we would still like PRs to be green for merging.

test: remove go mod tidy test from ci

---

pkg/apis/core/validation/validation_test.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/dns.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/dns_test.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/errors.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/kube.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/kube_test.go
staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta_test.go
staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go
staging/src/k8s.io/apimachinery/pkg/util/validation/validation_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/format/doc_test.go

I decided the fixes to tests were too risky for now and reverted the message changes.  The dns-label and qualified-name code is now a DIRECT port from the old.

Validation gen fix tests revert msg changes

---

staging/src/k8s.io/apimachinery/pkg/api/validate/limits.go
staging/src/k8s.io/apimachinery/pkg/api/validate/limits_test.go
staging/src/k8s.io/apimachinery/pkg/api/validate/strfmt.go
staging/src/k8s.io/apimachinery/pkg/api/validate/strfmt_test.go
staging/src/k8s.io/apimachinery/pkg/api/validate/testing.go
staging/src/k8s.io/apimachinery/pkg/api/validate/testing_test.go
staging/src/k8s.io/apimachinery/pkg/util/validation/field/errors.go

This PR adds the Origin to the Invalid() errors from the generated validations.
Note: It doesn't include the Invalid errors for the "union" as it is still being decided on the naming for it.

Add Origin to Invalid errors for generated validations

---

hack/update-codegen.sh
staging/src/k8s.io/code-generator/cmd/validation-gen/main.go
staging/src/k8s.io/code-generator/cmd/validation-gen/targets.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/opaque.go

From offline discussion, --readonly-pkg is preferred to --extra-pkg in validation-gen
Will make a PR upstream for this once merged into the dev branch

chore(validation-gen): rename flag --extra-pkg -> --readonly-pkg in validation-gen

---

pkg/registry/core/replicationcontroller/strategy.go
staging/src/k8s.io/apiserver/pkg/registry/rest/validate.go
staging/src/k8s.io/apiserver/pkg/registry/rest/validate_test.go
staging/src/k8s.io/apiserver/pkg/validation/metrics.go
staging/src/k8s.io/apiserver/pkg/validation/metrics_test.go

This PR adds the declarative_validation_mismatch_total metric as well as runtime verification testing to validation-gen

feat: add declarative_validation_mismatch_total metric and associated declarative validation runtime verification tests

---

pkg/apis/core/v1/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

Based on deads feedback, this is simple.  Might be nice to save comments with tag name and flags, and sort them into Functions so the they can be interleaved, but that is much larger work.

Emit comments before validation code (dev branch)

---

staging/src/k8s.io/apiserver/pkg/registry/rest/validate.go
staging/src/k8s.io/apiserver/pkg/registry/rest/validate_test.go

Related upstream PR: https://github.com/kubernetes/kubernetes/pull/130754

chore: change Info->Error log level related to declarative validation runtime tests and refactor panic wrapper names

---

hack/update-codegen.sh
hack/verify-api-lint.sh
staging/src/k8s.io/code-generator/cmd/validation-gen/lint.go
staging/src/k8s.io/code-generator/cmd/validation-gen/lint_rules.go
staging/src/k8s.io/code-generator/cmd/validation-gen/lint_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/main.go
staging/src/k8s.io/code-generator/cmd/validation-gen/targets.go

Results in errors like:
```
$ ./hack/verify-api-lint.sh
+++ [0317 09:00:04] Generating validation code for 69 targets
F0317 09:00:05.637556 1049736 targets.go:363] lint failed:
type k8s.io/api/core/v1.PodAffinityTerm:
field LabelSelector: conflicting tags: {+k8s:optional, +k8s:required}: fields cannot be both optional and required
field Namespaces: conflicting tags: {+default, +k8s:required}: fields with default values are always optional
!!! [0317 09:00:05] Call tree:
!!! [0317 09:00:05]  1: hack/update-codegen.sh:1132 codegen::validation(...)
```

Add API lint to verify scripts

---

staging/src/k8s.io/code-generator/cmd/validation-gen/targets.go

Without this we visit some types twice.
This produces no changes to generated code.

Create a single TypeDiscoverer for all inputs
