jpbetz/kubernetes

staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/compilation.go
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/compilation_test.go
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation.go

**What this PR does / why we need it**:
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
**Special notes for your reviewer**:
**Release note**:
```release-note
```

Use pointer for compilation error.

---

staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation.go

**What this PR does / why we need it**:
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
**Special notes for your reviewer**:
**Release note**:
```release-note
```

Fix bug in validator.

---

TODO.validation-gen
staging/src/k8s.io/code-generator/cmd/validation-gen/generators/targets.go

Add TODO file

---

TODO.validation-gen
pkg/apis/apps/v1/zz_generated.validations.go
pkg/apis/core/v1/zz_generated.validations.go
pkg/apis/core/validation/validation.go
staging/src/k8s.io/api/core/v1/types.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/dns.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/doc.go
staging/src/k8s.io/apimachinery/pkg/api/validate/content/errors.go
staging/src/k8s.io/apimachinery/pkg/api/validate/doc.go
staging/src/k8s.io/apimachinery/pkg/api/validate/errors.go
staging/src/k8s.io/apimachinery/pkg/api/validate/net.go
staging/src/k8s.io/apimachinery/pkg/api/validate/schema.go
staging/src/k8s.io/apimachinery/pkg/api/validate/strfmt.go
staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/enum.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/openapi.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/registry.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/required.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/validators.go
staging/src/k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1/zz_generated.validations.go

This does exactly 1 new field to demonstrate.

Validate +required and +format=dns-label declaratively

---

TODO.validation-gen
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/maps/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/maps/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/one_type_match/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/one_type_match/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/pointers/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/pointers/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/primitives/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/primitives/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/slices/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/slices/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

Review commit-by-commit.  Read the output tests with a skeptical eye and see if we STILL missed something?

Fix generator bugs in eachVal/eachKey

---

staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/ordering/structs/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/ordering/structs/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/ordering/typedefs/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/ordering/typedefs/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/required.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/testing.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/validators.go

Rename Fatal to ShortCircuit

---

staging/src/k8s.io/apimachinery/pkg/api/validate/union.go
staging/src/k8s.io/apimachinery/pkg/api/validate/union_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/discriminated_union/docs_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/discriminated_union_custom_members/docs_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/multiple_discriminated_unions/docs_test.go

/kind bug
1. Update union validation error message.
2. Fix union validation unittest.
Fixes #43 
```release-note
NONE
```
```docs
```

fix: Update union

---

pkg/apis/core/v1/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

/kind bug
Update validation-gen generator to add pointer prefix for Status subresource
Fixes #42 
```release-note
None
```
```docs
```

fix: update generator to add pointer prefix for status type

---

staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

Don't support pointers to slices or maps

---

pkg/apis/core/v1/zz_generated.validations.go
staging/src/k8s.io/apimachinery/pkg/api/validate/schema.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/forbidden/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/forbidden/docs_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/forbidden/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/optional/testdata/validate-false.json
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/optional/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/recursive/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/required/testdata/validate-false.json
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/required/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/discriminated_union/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/discriminated_union_custom_members/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/multiple_discriminated_unions/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/multiple_unions/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/union/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/unions/union_custom_members/zz_generated.validations.go
staging/src/k8s.io/code-generator/cmd/validation-gen/validators/required.go

/kind feature
`Required`, `Optional` and `Forbidden` may take in non-comparable and non-pointer value, update the validation function to handle these cases.
Fixes #42 1st and 2nd bullet point.
```release-note
NONE
```
```docs
```

fix: Handle non-comparable and non-pointer in schema validation

---

staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/forbidden/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/forbidden/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/forbidden/zz_generated.validations.go

Remove T2 from forbidden test case

---

staging/src/k8s.io/apimachinery/pkg/api/validate/schema_test.go
staging/src/k8s.io/apimachinery/pkg/util/validation/field/errors.go

This would have caught the previous bug in +required

Add a test for schema validation

---

staging/src/k8s.io/code-generator/cmd/validation-gen/testscheme/testscheme.go

cmp.Diff does not sort maps by default.

Nicer errors in testscheme

---

staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

It sort of fell into disrepair and is not actually that useful.  Less code is more better.

Remove 'dump()' logic

---

staging/src/k8s.io/code-generator/cmd/validation-gen/main.go

/kind bug
Before:
```
"Payloads": [
{
"Description": "\u003cnone\u003e"
},
```
After:
```
"Payloads": [
{
"Description": "<none>"
},
```

fix: Fixes HTML escaping in validation printDocs

---

staging/src/k8s.io/code-generator/cmd/validation-gen/main.go

fix: update NewValidator in printDocs

---

staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta_test.go
staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/format/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/subfield/nonincluded/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/subfield/nonincluded/testdata/validate-false.json
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/subfield/validatefalse/testdata/validate-false.json

Without CI we have been a bit sloppy.

Fix tests broken in earlier changes

---

TODO.validation-gen

Fixes #
```release-note
```
```docs
```

update Validation-gen todo

---

staging/src/k8s.io/code-generator/cmd/validation-gen/validators/required.go

Related:
https://github.com/kubernetes/kubernetes/pull/130349#discussion_r1968197103

resolve issue with flipped requirednessRequired and requirednessOptional docs

---

vendor/modules.txt

Fix the only merge conflict, so CI can run and have signal when Joe wakes up.

Manual fix to merge conflict

---

hack/update-codegen.sh
staging/src/k8s.io/code-generator/cmd/validation-gen/validation.go

Fix opaque on dev branch

---

staging/src/k8s.io/code-generator/cmd/validation-gen/generate_docs.sh
staging/src/k8s.io/code-generator/cmd/validation-gen/validation_tags.md

Fixes #
```release-note
```
```docs
```

Add script to generate validation tags documentation

---

pkg/apis/core/validation/validation.go
pkg/apis/core/validation/validation_test.go
pkg/features/kube_features.go
pkg/features/versioned_kube_features.go
pkg/registry/core/pod/strategy.go
pkg/registry/core/replicationcontroller/strategy.go
pkg/registry/core/replicationcontroller/strategy_test.go
staging/src/k8s.io/apimachinery/pkg/util/validation/field/errors.go
staging/src/k8s.io/apimachinery/pkg/util/validation/field/errors_test.go
test/featuregates_linter/test_data/versioned_feature_list.yaml

- Introduce CoveredByDeclarative flag to Error struct
- cherry-pick featuregate update change
- fix compile error
- verify equivalence based on CoveredByDeclarative

Add CoveredByDeclarative to error struct

---

pkg/apis/core/validation/validation_test.go
pkg/features/versioned_kube_features.go
staging/src/k8s.io/apimachinery/pkg/api/validate/testing_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/generate_docs.sh
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/format/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/format/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxitems/slice_of_primitive/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxitems/slice_of_primitive/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxitems/slice_of_struct/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxitems/slice_of_struct/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxitems/typedef_to_slice/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxitems/typedef_to_slice/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxlength/doc.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/maxlength/doc_test.go
staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/tags/minimum/doc_test.go
test/compatibility_lifecycle/reference/versioned_feature_list.yaml

This drops things that are different than master that we don't intend to upstream and fixes some things (boilerplate) that will be problems when we do.

Clean up small diffs vs master
